export enum Configs {
  NODE_ENV = 'NODE_ENV',
  MONGO_DB_URI = 'MONGO_DB_URI',
  PORT = 'PORT',
  STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY',
  STRIPE_BASE_URL = 'STRIPE_BASE_URL',
  PAYSTACK_SECRET_KEY = 'PAYSTACK_SECRET_KEY',
  PAYSTACK_BASE_URL = 'PAYSTACK_BASE_URL',
  POOL_WALLET_PRIVATE_KEY = 'POOL_WALLET_PRIVATE_KEY',
  CHECKOUT_BASE_URL = 'CHECKOUT_BASE_URL',
  BASESCAN_BASE_URL = 'BASESCAN_BASE_URL',
  BASESCAN_API_KEY = 'BASESCAN_API_KEY',
}
